### ISSUE TITLE
Not an issue: Question

### ISSUE THREAD

**Issue by sincze** [bluewalk/bimmer_connected-api#1]
This is the next project after the PHP version has been archived ??

**Comment by bluewalk** [comment]
Yes for me personally it's the replacement as bimmer_connected is being actively maintained.

**Comment by sincze** [comment]
I must admit, this is a pretty smart idea! As the basis bimmer_connected is indeed maintained regularly 
Currently it reads the stats. I would like to add the possibility to send something as well to the car ;-)
